-- Auto-generated by Inkura schema generator
-- Migration: 002_projects.sql
-- Entity:    projects

-- ── updated_at trigger function ─────────────────────────────────────────────
-- Create once; reused by every table that has timestamps.
-- SECURITY DEFINER + SET search_path = public matches the auth generator pattern.

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

-- ── Table: projects ────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.projects (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title                  TEXT NOT NULL,
  status                 TEXT CHECK (status IN ('draft', 'active', 'completed')) DEFAULT 'draft',
  owner_id               UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── Row Level Security ──────────────────────────────────────────

ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can select projects"
  ON public.projects FOR SELECT
  TO authenticated
  USING (owner_id = auth.uid());

CREATE POLICY "Authenticated users can insert projects"
  ON public.projects FOR INSERT
  TO authenticated
  WITH CHECK (owner_id = auth.uid());

CREATE POLICY "Authenticated users can update projects"
  ON public.projects FOR UPDATE
  TO authenticated
  USING (owner_id = auth.uid());

CREATE POLICY "Authenticated users can delete projects"
  ON public.projects FOR DELETE
  TO authenticated
  USING (owner_id = auth.uid());

-- ── Indexes ────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS projects_status_idx ON public.projects(status);
CREATE INDEX IF NOT EXISTS projects_owner_id_idx ON public.projects(owner_id);

-- ── Triggers ───────────────────────────────────────────────────

CREATE TRIGGER set_projects_updated_at
  BEFORE UPDATE ON public.projects
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
