-- Auto-generated by Inkura schema generator
-- Seed data for local development and testing
-- Safe to re-run (uses ON CONFLICT DO NOTHING)

-- ── Seed user (must exist in auth.users first) ───────────────────────────────
-- In Supabase Studio: Authentication → Users → Add user
-- Then update the UUID below to match, or use this as a placeholder.
-- Placeholder user ID: 00000000-0000-0000-0000-000000000001

-- ── projects ────────────────────────────────────────────────────

INSERT INTO public.projects (id, title, status, owner_id)
VALUES ('00000001-0000-0000-0000-000000000001', 'Sample title 1', 'draft', '00000000-0000-0000-0000-000000000001')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.projects (id, title, status, owner_id)
VALUES ('00000001-0000-0000-0000-000000000002', 'Sample title 2', 'active', '00000000-0000-0000-0000-000000000001')
ON CONFLICT (id) DO NOTHING;
